/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { EstudioMedicoService } from "../estudioMedico.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { EstudioMedicoCreateInput } from "./EstudioMedicoCreateInput";
import { EstudioMedico } from "./EstudioMedico";
import { EstudioMedicoFindManyArgs } from "./EstudioMedicoFindManyArgs";
import { EstudioMedicoWhereUniqueInput } from "./EstudioMedicoWhereUniqueInput";
import { EstudioMedicoUpdateInput } from "./EstudioMedicoUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class EstudioMedicoControllerBase {
  constructor(
    protected readonly service: EstudioMedicoService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: EstudioMedico })
  @nestAccessControl.UseRoles({
    resource: "EstudioMedico",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createEstudioMedico(
    @common.Body() data: EstudioMedicoCreateInput
  ): Promise<EstudioMedico> {
    return await this.service.createEstudioMedico({
      data: {
        ...data,

        paciente: data.paciente
          ? {
              connect: data.paciente,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        tipo: true,
        fecha: true,
        resultado: true,

        paciente: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [EstudioMedico] })
  @ApiNestedQuery(EstudioMedicoFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "EstudioMedico",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async estudioMedicos(
    @common.Req() request: Request
  ): Promise<EstudioMedico[]> {
    const args = plainToClass(EstudioMedicoFindManyArgs, request.query);
    return this.service.estudioMedicos({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        tipo: true,
        fecha: true,
        resultado: true,

        paciente: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: EstudioMedico })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "EstudioMedico",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async estudioMedico(
    @common.Param() params: EstudioMedicoWhereUniqueInput
  ): Promise<EstudioMedico | null> {
    const result = await this.service.estudioMedico({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        tipo: true,
        fecha: true,
        resultado: true,

        paciente: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: EstudioMedico })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "EstudioMedico",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateEstudioMedico(
    @common.Param() params: EstudioMedicoWhereUniqueInput,
    @common.Body() data: EstudioMedicoUpdateInput
  ): Promise<EstudioMedico | null> {
    try {
      return await this.service.updateEstudioMedico({
        where: params,
        data: {
          ...data,

          paciente: data.paciente
            ? {
                connect: data.paciente,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          tipo: true,
          fecha: true,
          resultado: true,

          paciente: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: EstudioMedico })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "EstudioMedico",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteEstudioMedico(
    @common.Param() params: EstudioMedicoWhereUniqueInput
  ): Promise<EstudioMedico | null> {
    try {
      return await this.service.deleteEstudioMedico({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          tipo: true,
          fecha: true,
          resultado: true,

          paciente: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
