/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringFilter } from "../../util/StringFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { TurnoListRelationFilter } from "../../turno/base/TurnoListRelationFilter";
import { EstudioMedicoListRelationFilter } from "../../estudioMedico/base/EstudioMedicoListRelationFilter";

@InputType()
class PacienteWhereInput {
  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  nombre?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  apellido?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  fechaNacimiento?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  dni?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => TurnoListRelationFilter,
  })
  @ValidateNested()
  @Type(() => TurnoListRelationFilter)
  @IsOptional()
  @Field(() => TurnoListRelationFilter, {
    nullable: true,
  })
  turnos?: TurnoListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => EstudioMedicoListRelationFilter,
  })
  @ValidateNested()
  @Type(() => EstudioMedicoListRelationFilter)
  @IsOptional()
  @Field(() => EstudioMedicoListRelationFilter, {
    nullable: true,
  })
  estudioMedicos?: EstudioMedicoListRelationFilter;
}

export { PacienteWhereInput as PacienteWhereInput };
